package com.gengzi.reranker.response;

import org.springframework.ai.model.ModelResponse;

import java.util.List;
import java.util.Map;

public class RerankerModelResponse implements ModelResponse<RerankModelResult> {


    private RerankResponse rerankResponse;

    // 全部重排序结果列表（对应 JSON 中的 results）
    private List<RerankModelResult> results;

    private RerankResponseMetadata responseMetadata;

    public RerankerModelResponse(RerankResponse rerankResponse) {
        this.rerankResponse = rerankResponse;
        // 解析响应结果
        // 转换原始响应为 ModelResult 列表
        this.results = rerankResponse.getResults().stream()
                .map(result -> new RerankModelResult(
                        new RerankResultData(
                                "",
                                result.getIndex(),
                                result.getRelevance_score()
                        ),
                        null // 单个结果的元信息（可选）
                ))
                .toList();

        this.responseMetadata = new RerankResponseMetadata(Map.of(
                "id", rerankResponse.getId()
        ));


    }


    /**
     * Retrieves the result of the AI model.
     *
     * @return the result generated by the AI model
     */
    @Override
    public RerankModelResult getResult() {
        return results.isEmpty() ? null : results.get(0); // 默认返回第一个结果
    }

    /**
     * Retrieves the list of generated outputs by the AI model.
     *
     * @return the list of generated outputs
     */
    @Override
    public List<RerankModelResult> getResults() {
        return results;
    }

    /**
     * Retrieves the response metadata associated with the AI model's response.
     *
     * @return the response metadata
     */
    @Override
    public RerankResponseMetadata getMetadata() {
        return responseMetadata;
    }
}
