package com.gengzi.reranker.response;

import org.springframework.ai.model.ModelResult;
import org.springframework.ai.model.ResultMetadata;

public class RerankModelResult implements ModelResult<RerankResultData> {


    private RerankResultData rerankResultData;
    private RerankResultMetadata rerankResultMetadata;

    public RerankModelResult(RerankResultData rerankResultData, RerankResultMetadata rerankResultMetadata) {
        this.rerankResultData = rerankResultData;
        this.rerankResultMetadata = rerankResultMetadata;
    }

    /**
     * Retrieves the output generated by the AI model.
     *
     * @return the output generated by the AI model
     */
    @Override
    public RerankResultData getOutput() {
        return rerankResultData;
    }

    /**
     * Retrieves the metadata associated with the result of an AI model.
     *
     * @return the metadata associated with the result
     */
    @Override
    public ResultMetadata getMetadata() {
        return rerankResultMetadata;
    }
}
